server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webmvc:
          discovery:
            locator:
              enabled: false
              low-case-service-id: true
          routes:
            - id: catalog-service
              uri: lb://catalog-service
              predicates:
                - Path=/api/catalog/**
            - id: inventory-service
              uri: lb://inventory-service
              predicates:
                - Path=/api/inventory/**
#            - id: payment-service
#              uri: lb://payment-service
#              predicates:
#                - Path=/api/payments/**
            - id: order-service
              uri: lb://order-service
              predicates:
                - Path=/api/order/**
